name: Submodule Trigger

on:
  repository_dispatch:
    types: [submodule-updated]

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      # 拉取主仓库代码并初始化子模块
      - name: Clone Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.SUBMODULE_PAT }}  # 确保 SUBMODULE_PAT 已配置

      # 调试步骤：检查子模块是否被正确拉取
      - name: Check Submodule
        run: |
          ls -la content

      # 触发主仓库的部署流程
      - name: Trigger Deploy
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            "https://api.github.com/repos/xushuosean/xushuosean.github.io/dispatches" \
            -d '{"event_type": "submodule-updated"}'